### ISSUE TITLE
Nobles_barracks_mexica grammatical issue

### ISSUE THREAD

**Issue by mrlie58** [0ADMods/pre-colonial-mod#14]
![grafik](https://user-images.githubusercontent.com/60375368/87630203-e1dff880-c734-11ea-81d6-e5f996d510df.png)

**Comment by Osimedias** [comment]
Done

**Comment by Osimedias** [comment]
Is Fixed?
So i can close this issue.

**Comment by mrlie58** [comment]
> 
> 
> Is Fixed?
> So i can close this issue.

Yes, it's fine

**Comment by Osimedias** [comment]
Fixed :D
