### ISSUE TITLE
Commit messages. Also Textures.

### ISSUE THREAD

**Issue by mithrayls** [0ADMods/pre-colonial-mod#17]
I'm following your mod with interest so I would love to see more interesting commit messages :-)

By the way, I was wondering about the very bright red textures you have for the Mexica structures. Is there a reason why you have chosen the bright red color? I think it would look nicer if it looked a more natural rock.

**Comment by Osimedias** [comment]
Are you refering to the textures of the walls and fortress?
they are the zapotec wallset and fortress.
Historicaly the Zapotec Buildings are red with some varius colors.
Also olny important commits have a descriptible mesages ,the less important only have "commit" as messages(Most are quick fixes).

**Comment by Osimedias** [comment]
Also i dont made the Mexica texture xd

**Comment by mithrayls** [comment]
![zapotec](https://user-images.githubusercontent.com/46880236/89394840-aeefba00-d760-11ea-9b84-bb7d594de19e.png)

**Comment by Osimedias** [comment]
Is strange that Zapotec buildings appear to you instead of Mexicas.
The Mexicas are this:
![screenshot0062](https://user-images.githubusercontent.com/7454459/89441977-9d33f580-d713-11ea-9a7c-7e159198c228.png)
